### PR TITLE
Added new logrotate config file

### PR DESCRIPTION
**Pull request by markunsworth**
Replaces the default logrotate config when using upstart in favour of init.d

### CODE REVIEW

**Comment by jjasghar** [comment]
Can you add some specs for this? I'd like to make sure that our testing covers this. It seems odd that we don't already.

After that I'll pull this PR down verify it myself then when i get another :+1: I'll merge.

**Comment by ptqa** [comment]
I personally don't like this approach of creating logrotate templates. What's wrong with https://github.com/stevendanna/logrotate cookbook?

**Comment by markunsworth** [comment]
@ptqa Happy to use the logrotate cookbook if no one has an issue with that as a dependency. I hadn't come across it before but I like "the cut of it's jib". 
WRT to hardcoding, i just replicated what was automatically installed by the deb package. Have just tweaked that particular value to make it configurable

**Comment by jjasghar** [comment]
> Also all values are hardcoded, what if I don't need 20 days? IMHO it should be defined as attribute

I agree with this, but at the same time it's out of scope.

>  WRT to hardcoding, i just replicated what was in the config that was automatically installed by the deb package. 

Perfect. If that's the *cough* sane *cough* default that the pkg gives us that's good enough for me.

**Comment by jjasghar** [comment]
@markunsworth can you take care of the travis failures?

**Comment by jjasghar** [comment]
Closed due to already in the code? It's here, i dunno how it got here though.

**Pull request closed without merging**
