### PR TITLE
Convert all LWRPs to custom resources

### PR DESCRIPTION
**Pull request by fozboz**
Modernizes the cookbook to use custom resources instead of LWRPs.

Includes a few touch-ups to the dokken test suites.

There are still some dokken test suites not fully working for me. Neither of the amazonlinux tests are passing, because for some reason the `service` inspec resource is not working.
I also can't get the opensuse suite to work because zypper is waiting for human input to import the erlang GPG key. I didn't want to put too much effort in to fixing this because I don't see how this resource would ever have worked; it never existed!

### CODE REVIEW

**Comment by michaelklishin** [comment]
Yes, AL2022 doesn't pass for me either for reasons I cannot understand. It's as if `dnf`/`yum` package resolution settings are different from Fedora 34. We can temporarily remove it from the matrix.

**Comment by michaelklishin** [comment]
Thank you, this ended up being a substantial amount of work!

**Comment by michaelklishin** [comment]
@fozboz would you like me to add you as a collaborator to this repo?

**Comment by fozboz** [comment]
Sure, thanks @michaelklishin

**Comment by michaelklishin** [comment]
@fozboz done ✅

**Pull request merged**
