### PR TITLE
Add missing notifies for ohai[reload_packages] on Fedora/RHEL

### PR DESCRIPTION
**Pull request by ramereth**
Without this, it doesn't properly run ``installed_rabbitmq_version`` and causes
an error:

```
  * ohai[reload_packages] action nothing (skipped due to action :nothing)
Recipe: rabbitmq::management_ui
  * rabbitmq_plugin[rabbitmq_management] action enable

    ================================================================================
    Error executing action `enable` on resource 'rabbitmq_plugin[rabbitmq_management]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `[]' for nil:NilClass

    Cookbook Trace: (most recent call first)
    ----------------------------------------
    /tmp/kitchen/cache/cookbooks/rabbitmq/libraries/default.rb:79:in `installed_rabbitmq_version'
    /tmp/kitchen/cache/cookbooks/rabbitmq/providers/plugin.rb:26:in `plugin_enabled?'
    /tmp/kitchen/cache/cookbooks/rabbitmq/providers/plugin.rb:40:in `block in class_from_file'
```

Signed-off-by: Lance Albertson <lance@osuosl.org>

## Proposed Changes

Please describe the big picture of your changes here to communicate to the
RabbitMQ team why we should accept this pull request. If it fixes a bug or
resolves a feature request, be sure to link to that issue.

A pull request that doesn't explain **why** the change was made has a much
lower chance of being accepted.

If English isn't your first language, don't worry about it and try to
communicate the problem you are trying to solve to the best of your abilities.
As long as we can understand the intent, it's all good.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [ ] I have read the `CONTRIBUTING.md` document
- [ ] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did and what alternatives you
considered, etc.

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you!

**Comment by michaelklishin** [comment]
@ramereth as far as I can tell this is not applicable for `master`. Can you please confirm? #555 seems highly relevant.

**Comment by ramereth** [comment]
@michaelklishin that seems correct. Can you please publish a new release for 5.x which includes this and #561?

**Comment by ramereth** [comment]
@michaelklishin ping on a new release please?

**Comment by michaelklishin** [comment]
A new release is coming after I have a chance to run all tests locally, for all configuration. Should happen in the next 12 hours or so.

**Comment by michaelklishin** [comment]
[`5.8.5` is up](https://supermarket.chef.io/cookbooks/rabbitmq) in Chef Supermarket.

**Pull request merged**
