### PR TITLE
added node_name_to_join to verify the joined_cluster

### PR DESCRIPTION
**Pull request by riveryc**
Make sure that cookbook will surely add node to the cluster no matter it's in itself cluster or not.
Double check the current cluster name matches the to_be_joined cluster.

### CODE REVIEW

**Comment by lamont** [comment]
Digging into the failure, the chef_version missing method in metadata.rb can be resolved by updating ridley from 4.5 to 4.6 but I'm not sure if I can just update the Gemfile or if i need to edit the Gemfile.lock

**Comment by michaelklishin** [comment]
@lamont `Gemfile.lock` is updated with `bundle update` after `Gemfile` changes.

**Comment by lamont** [comment]
Since the Gemfile currently does not refer to explicit versions of anything, and I want to suggest the 4.6 version of ridley for the travis run, is my best bet then to add a version constraint to the Gemfile, bundle update then check both it and the generated Gemfile.lock in?

Alternately we could remove the chef_version method from the metadata.rb as not a lot of people are trying to use chef11 these days.

**Comment by michaelklishin** [comment]
@lamont pinning a specific gem is fine. Take a look at [rubygems version patterns](http://guides.rubygems.org/patterns/) and [Bundler gemfile docs](http://bundler.io/v1.13/gemfile.html) about how to do it ;)

**Comment by michaelklishin** [comment]
@lamont I *think* that dropping Chef 11 support might be an option, too, but will leave it to @jjasghar to decide on that.

**Comment by devsibwarra** [comment]
People were using Chef 11 and still reporting issues, so I had suggested the `chef_version` restriction.  Looks like @jjasghar just removed it in v4.10.0, so hopefully your tests are successful now

**Comment by jjasghar** [comment]
Chef 11 is no longer supported. please look at the readme.

**Pull request closed without merging**
