### PR TITLE
Remove lock on erlang

### PR DESCRIPTION
**Pull request by scalp42**
Thoughts?

### CODE REVIEW

**Comment by jjasghar** [comment]
I like the idea of it being pinned. It's safe and tested. I'm willing to move the versions though. Is there something in the newer `erlang` cookbook you'd like?

**Comment by scalp42** [comment]
@jjasghar I was getting some dependencies issues with other cookbooks. Unfortunately, only rabbitmq locks the dependencies.

I'll give it another try today adding back the lock, see what the issue was.

**Comment by michaelklishin** [comment]
@scalp42 sorry, any updates on this?

**Comment by jjasghar** [comment]
I've got this in the 5.0.0 release. :)

**Pull request closed without merging**
