### PR TITLE
simplify switchcase for rabbitmq plugins command

### PR DESCRIPTION
**Pull request by jklare**
## Proposed Changes

Use new method installed_rabbitmq_version to simplify switchcases
for plugins command.

## Types of Changes

- [x] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [ ] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you!

**Comment by chalb** [comment]
I'll really like this PR. Quick question: When will this be released?

**Comment by michaelklishin** [comment]
No earlier than we have some feedback and decision made for #521.

**Comment by chalb** [comment]
Fair enough. Thank you for your advise!

**Comment by michaelklishin** [comment]
So #521 is addressed as far as I'm concerned. I'd appreciate some sanity checking of the tip of the `v5.x` branch, then we can produce a new patch release.

**Pull request merged**
